#!/usr/bin/env ruby

require 'rails/commands/server'
require 'rack'
require 'webrick'
require 'webrick/https'

module Rails
    class Server < ::Rack::Server
        def default_options
             

            super.merge({
                :Port => 3000,
                :environment => (ENV['RAILS_ENV'] || "development").dup,
                :daemonize => false,
                :debugger => false,
                :pid => File.expand_path("tmp/pids/server.pid"),
                :config => File.expand_path("config.ru"),
                :SSLEnable => true,
                :SSLPrivateKey => OpenSSL::PKey::RSA.new(File.read('/usr/src/redmine/ssl/private/domain.key'), ''),
                :SSLCertificate => OpenSSL::X509::Certificate.new(File.read('/usr/src/redmine/ssl/certs/domain.crt')),
                :SSLCACertificateFile => '/usr/src/redmine/ssl/certs/intermediate.pem',
                :SSLCertName => [["CN", WEBrick::Utils::getservername]]
            })
        end
    end
end



APP_PATH = File.expand_path('../../config/application',  __FILE__)
require_relative '../config/boot'
require 'rails/commands'
